kind: Deployment
apiVersion: apps/v1
metadata:
  name: smart-home
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smart-home
  template:
    metadata:
      labels:
        app: smart-home
    spec:
      containers:
        - name: smart-home
          image: localhost:5000/smart-home
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: smart-home
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: smart-home
